[project]
name = "beats-feature-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "fairseq>=0.12.2",
    "moviepy>=1.0.3",
    "soundfile>=0.13.1",
    "torchaudio>=2.7.0",
    "tqdm>=4.67.1",
]
