# config/features.yaml

features:
  aud_last: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/aud_last"
  aud_ln_post: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/audio_ln_post"
  conv3d_features: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/conv3d_features"
  vis_block5: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block5"
  vis_block8: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block8"
  vis_block12: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block12"
  vis_merged: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_merged"
  thinker_12: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_12"
  thinker_24: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_24"
  thinker_36: "features/Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_36"
  text: "features/Text/Qwen3B_tr1.49_len60_before50"
  fast_res3_act: "features/Visual/SlowFast_R101_tr1.49/fast_res3_act"
  fast_stem_act: "features/Visual/SlowFast_R101_tr1.49/fast_stem_act"
  pool_concat: "features/Visual/SlowFast_R101_tr1.49/pool_concat"
  slow_res3_act: "features/Visual/SlowFast_R101_tr1.49/slow_res3_act"
  slow_res5_act: "features/Visual/SlowFast_R101_tr1.49/slow_res5_act"
  slow_stem_act: "features/Visual/SlowFast_R101_tr1.49/slow_stem_act"
  audio_long_context: "features/Audio/Wave2Vec2/features_chunk1.49_len60_before50"

input_dims:
  aud_last: 2560
  aud_ln_post: 2560
  #conv3d_features: 2560
  #vis_block5: 2560
  vis_block8: 2560
  #vis_block12: 2560
  vis_merged: 4096
  #thinker_12: 4096
  thinker_24: 4096
  #thinker_36: 4096
  text: 2048
  #fast_res3_act: 2048
  #fast_stem_act: 1024
  pool_concat: 9216
  slow_res3_act: 4096
  #slow_res5_act: 4096
  #slow_stem_act: 8192
  audio_long_context: 2048

data_dir: "data/fmri"