# config/features.yaml

features:
  aud_last: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/aud_last"
  aud_ln_post: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/audio_ln_post"
  conv3d_features: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/conv3d_features"
  vis_block5: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block5"
  vis_block8: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block8"
  vis_block12: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_block12"
  vis_merged: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/vis_merged"
  thinker_12: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_12"
  thinker_24: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_24"
  thinker_36: "Omni/Qwen2.5_3B/features_tr1.49_len8_before6/thinker_36"
  text: "Emotional/Qwen2.5_14_Full_tr1.49"
  fast_res3_act: "Visual/SlowFast_R101_tr1.49/fast_res3_act"
  fast_stem_act: "Visual/SlowFast_R101_tr1.49/fast_stem_act"
  pool_concat: "Visual/SlowFast_R101_tr1.49/pool_concat"
  slow_res3_act: "Visual/SlowFast_R101_tr1.49/slow_res3_act"
  slow_res5_act: "Visual/SlowFast_R101_tr1.49/slow_res5_act"
  slow_stem_act: "Visual/SlowFast_R101_tr1.49/slow_stem_act"
  audio_long_context: "Audio/Wave2Vec2/features_chunk1.49_len60_before50"
  qwen_emotional: "Emotional/Qwen2.5_14_Full_tr1.49"

input_dims:
  aud_last: 2560
  aud_ln_post: 2560
  #conv3d_features: 2560
  #vis_block5: 2560
  vis_block8: 2560
  #vis_block12: 2560
  vis_merged: 4096
  #thinker_12: 4096
  #thinker_24: 4096
  thinker_36: 4096
  text: 5120
  #fast_res3_act: 2048
  #fast_stem_act: 1024
  pool_concat: 9216
  slow_res3_act: 4096
  #slow_res5_act: 4096
  #slow_stem_act: 8192
  audio_long_context: 2048
  #qwen_emotional: 5120 
  #audio_mfcc_mono: 128
  #audio_mfcc_stereo: 128