# ------------------------------ Data-loading ------------------------------
data:
  batch_size:                4      
  train_noise_std:           0.0
  use_normalization:         false
  val_name:                  "s06"
  normalize_validation_bold: false
  shuffle_train:             true

  stratification_variable:   false # false or name of variable eg. "name" or "is_movie"

  # Performace tuning
  num_workers:               8
  prefetch_factor:           4
  persistent_workers:        true
  pin_memory:                true

# ------------------------------ Model ------------------------------
model:
  fuse_mode:                 "concat"      # e.g. "concat"
  hidden_dim:                256
  output_dim:                1000
  num_subjects:              4
  use_hrf_conv:              false
  learn_hrf:                 false

# ------------------------------ Optimizer / schedule ------------------------------
optim:
  weight_decay:              0.0001
  lr:                        0.0001
  grad_clip_max_norm:        5.0

# ------------------------------ Training loop ------------------------------
train:
  epochs:                    150
  early_stop_patience:       1

  lambda_sample:             0.0          # loss weights must be in params.yaml
  lambda_roi:                0.0
  lambda_mse:                0.01
  lambda_hrf:                0.000