# config/params.yaml

train:
  epochs: 150
  batch_size: 4
  lr: 0.0001
  weight_decay: 0.0001
  device: "cuda:0"
  early_stop_patience: 2
  lambda_sample: 0
  lambda_roi: 0
  lambda_mse: 0.05
  lambda_hrf: 1e-3
  fuse_mode: "concat"
  hidden_dim: 256
  use_hrf_conv: true
  learn_hrf: true