# config/features.yaml

features:
  aud_last: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/aud_last"
  aud_ln_post: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/audio_ln_post"
  conv3d_features: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/conv3d_features"
  vis_block5: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/vis_block5"
  vis_block8: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/vis_block8"
  vis_block12: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/vis_block12"
  vis_merged: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/vis_merged"
  thinker_12: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/thinker_12"
  thinker_24: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/thinker_24"
  thinker_36: "Omni/Qwen2.5_3B_LongerContext/features_tr1.49_win60.0_stride30.0/thinker_36"
  text: "Text/Qwen3B_tr1.49_len60_before50"
  fast_res3_act: "Visual/SlowFast_R101_tr1.49_no_center_crop/fast_res3_act"
  fast_stem_act: "Visual/SlowFast_R101_tr1.49_no_center_crop/fast_stem_act"
  pool_concat: "Visual/SlowFast_R101_tr1.49_no_center_crop/pool_concat"
  slow_res3_act: "Visual/SlowFast_R101_tr1.49_no_center_crop/slow_res3_act"
  slow_res5_act: "Visual/SlowFast_R101_tr1.49_no_center_crop/slow_res5_act"
  slow_stem_act: "Visual/SlowFast_R101_tr1.49_no_center_crop/slow_stem_act"
  audio_long_context: "Audio/Wave2Vec2/features_chunk1.49_len60_before50"
  qwen_emotional: "Emotional/Qwen2.5_14_Full_tr1.49"
  qwen_big: "Text/Qwen2.5_72B_Full_tr1.49/"
  audio_beats_high: "Audio/BEATS_Full_tr1.49_ctx10.0/high"
  audio_beats_low: "Audio/BEATS_Full_tr1.49_ctx10.0/low"
  audio_whisper_high: "Audio/WhisperV3-Large-ctx30-stereoFalse/high"
  audio_whisper_low: "Audio/WhisperV3-Large-ctx30-stereoFalse/low"
  vjepa2_vitl_final: "Vjepa2-Copy/outs_tr1.49_len6_before3/vjepa2_vitl_final_features"
  vjepa2_vitl_pred5: "Vjepa2-Copy/outs_tr1.49_len6_before3/vjepa2_vitl_predictor_5_layer_norm"
  vjepa2_vitl_enc18: "Vjepa2-Copy/outs_tr1.49_len6_before3/vjepa2_vitl_encoder_18_layer_norm2"
  vjepa2_ap: "Vjepa2-Copy/outs_tr1.49_len6_before3/v-jepa2-ac-classifier-out"
  vjepa2_ap_block0: "Vjepa2-Copy/outs_tr1.49_len6_before3/v-jepa2-ac-classifier-block0-fc2"
  vjepa2_ap_block_last: "Vjepa2-Copy/outs_tr1.49_len6_before3/v-jepa2-ac-classifier-block-last-fc2"
  audio_visual_features: "Visual/AVS_features"
  labse_pool_l3_5: "Text/labse_pre0_post0_tr1.49/pool_l3_5"
  labse_pool_l6_8: "Text/labse_pre0_post0_tr1.49/pool_l6_8"
  labse_pool_l8_10: "Text/labse_pre0_post0_tr1.49/pool_l8_10"

input_dims:
  # aud_last: 2560
  # aud_ln_post: 2560
  # conv3d_features: 2560
  # vis_block5: 2560
  # vis_block8: 2560
  # vis_block12: 2560
  # vis_merged: 4096
  # thinker_12: 4096
  # thinker_24: 4096
  # thinker_36: 4096
  # text: 2048
  fast_res3_act: 2048
  # fast_stem_act: 1024
  pool_concat: 9216
  slow_res3_act: 4096
  # slow_res5_act: 4096
  slow_stem_act: 8192
  # audio_long_context: 2048
  qwen_emotional: 5120
  # qwen_big: 8192
  audio_beats_high: 3072
  # audio_beats_low: 3072
  audio_whisper_high: 1280
  # audio_whisper_low: 1280
  # audio_mfcc_mono: 128
  # audio_mfcc_stereo: 128
  # vjepa2_vitl_final: 9216
  # vjepa2_vitl_pred5: 3456
  vjepa2_vitl_enc18: 9216
  # vjepa2_ap: 174
  # vjepa2_ap_block0: 9216
  vjepa2_ap_block_last: 9216
  # labse_pool_l3_5: 768
  # labse_pool_l6_8: 768
  # labse_pool_l8_10: 768