[project]
name = "qwen-feature-extraction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.8.1",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "transformers>=4.51.1",
]
